# Generated by Django 5.2 on 2025-05-02 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='image',
        ),
    ]
