# Generated by Django 5.2 on 2025-05-04 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizo', '0002_remove_question_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='quiz_attachments/', verbose_name='Файл')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Загружено')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='quizo.quiz', verbose_name='Викторина')),
            ],
            options={
                'verbose_name': 'Файл викторины',
                'verbose_name_plural': 'Файлы викторины',
            },
        ),
    ]
