# Generated by Django 5.2 on 2025-05-04 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizo', '0003_quizattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattachment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='quiz_images/'),
        ),
    ]
